"use client";

import { PieChart, Zap, TrendingUp, DollarSign } from "lucide-react";

export default function PrizePoolInfo({ draw }: { draw: any }) {
  if (!draw) return null;

  const jackpotAmount = (draw.total_pool * 0.40);

  return (
    <div className="mb-12">
      <div className="p-10 bg-zinc-950 border border-white/5 rounded-[3rem] mb-6 relative overflow-hidden group">
        <div className="absolute inset-0 bg-emerald-500/5 opacity-0 group-hover:opacity-100 transition-opacity blur-3xl rounded-full" />
        <div className="relative z-10">
          <span className="text-zinc-500 text-[10px] font-black uppercase tracking-[0.4em] mb-4 block text-center">Total Prize Pool</span>
          <h3 className="text-6xl md:text-7xl font-black italic tracking-tighter text-white text-center leading-none">
            £{draw.total_pool.toLocaleString()}
          </h3>
          <div className="mt-6 flex justify-center">
            <div className="px-4 py-1 bg-white/5 border border-white/10 rounded-full text-[8px] font-black uppercase tracking-widest text-zinc-500">
              Generated by dynamic global network participation
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      <div className="p-6 bg-zinc-900/30 border border-emerald-500/10 rounded-[2rem] flex flex-col justify-between relative overflow-hidden group">
        {draw.jackpot_carry > 0 && (
          <div className="absolute top-0 right-0 px-3 py-1 bg-emerald-500 text-black text-[8px] font-black uppercase tracking-tighter rounded-bl-xl shadow-lg">
            Rollover Added
          </div>
        )}
        <div className="flex items-center justify-between mb-4">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center">
            <Zap size={20} className="text-emerald-500" />
          </div>
          <span className="text-[10px] font-black uppercase tracking-widest text-zinc-600">Jackpot</span>
        </div>
        <div>
          <h4 className="text-zinc-500 text-[9px] font-black uppercase tracking-widest mb-1">5 Numbers</h4>
          <span className="text-2xl font-black italic text-emerald-400 uppercase tracking-tighter leading-none">
            £{jackpotAmount.toLocaleString()}
          </span>
          {draw.jackpot_carry > 0 && (
            <p className="text-[8px] text-emerald-500/50 font-bold uppercase mt-1 italic">
              Incl. £{draw.jackpot_carry.toLocaleString()} rollover
            </p>
          )}
        </div>
      </div>

      <div className="p-6 bg-zinc-900/30 border border-white/5 rounded-[2rem] flex flex-col justify-between">
        <div className="flex items-center justify-between mb-4">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center">
            <PieChart size={20} className="text-emerald-500" />
          </div>
          <span className="text-[10px] font-black uppercase tracking-widest text-zinc-600">Silver Pool</span>
        </div>
        <div>
          <h4 className="text-zinc-500 text-[9px] font-black uppercase tracking-widest mb-1">4 Numbers</h4>
          <span className="text-2xl font-black italic text-zinc-100 uppercase tracking-tighter leading-none">
            £{(draw.total_pool * 0.35).toLocaleString()}
          </span>
        </div>
      </div>

      <div className="p-6 bg-zinc-900/30 border border-white/5 rounded-[2rem] flex flex-col justify-between">
        <div className="flex items-center justify-between mb-4">
          <div className="w-10 h-10 rounded-xl bg-orange-500/10 flex items-center justify-center">
            <TrendingUp size={20} className="text-orange-500" />
          </div>
          <span className="text-[10px] font-black uppercase tracking-widest text-zinc-600">Bronze Pool</span>
        </div>
        <div>
          <h4 className="text-zinc-500 text-[9px] font-black uppercase tracking-widest mb-1">3 Numbers</h4>
          <span className="text-2xl font-black italic text-orange-500 uppercase tracking-tighter leading-none">
            £{(draw.total_pool * 0.25).toLocaleString()}
          </span>
        </div>
    </div>
  </div>
</div>
  );
}
